export const skills = [
  { name: "JavaScript", icon: "/assets/tech_logo/javascript.png" },
  { name: "React", icon: "/assets/tech_logo/reactjs.png" },
  { name: "Node.js", icon: "/assets/tech_logo/nodejs.png" },
  { name: "Express", icon: "/assets/tech_logo/express.png" },
  { name: "MongoDB", icon: "/assets/tech_logo/mongodb.png" },
  { name: "PostgreSQL", icon: "/assets/tech_logo/postgre.png" },
  { name: "Python", icon: "/assets/tech_logo/python.png" },
  { name: "C", icon: "/assets/tech_logo/c.png" },
  { name: "C++", icon: "/assets/tech_logo/cpp.png" },
  { name: "HTML", icon: "/assets/tech_logo/html.png" },
  { name: "CSS", icon: "/assets/tech_logo/css.png" },
  { name: "Git", icon: "/assets/tech_logo/git.png" },
  { name: "GitHub", icon: "/assets/tech_logo/github.png" },
  { name: "Bootstrap", icon: "/assets/tech_logo/bootstrap.png" },
  { name: "Next.js", icon: "/assets/tech_logo/nextjs.png" },
];
