export const skills = [
  { name: "JavaScript", icon: "/assets/tech_logo/javascript.png" },
  { name: "React", icon: "/assets/tech_logo/reactjs.png" },
  { name: "Node.js", icon: "/assets/tech_logo/nodejs.png" },
  { name: "Express", icon: "/assets/tech_logo/express.png" },
  { name: "MongoDB", icon: "/assets/tech_logo/mongodb.png" },
  { name: "PostgreSQL", icon: "/assets/tech_logo/postgre.png" },
  { name: "Python", icon: "/assets/tech_logo/python.png" },
  { name: "C", icon: "/assets/tech_logo/c.png" },
  { name: "C++", icon: "/assets/tech_logo/cpp.png" },
  { name: "HTML", icon: "/assets/tech_logo/html.png" },
  { name: "CSS", icon: "/assets/tech_logo/css.png" },
  { name: "Git", icon: "/assets/tech_logo/git.png" },
  { name: "GitHub", icon: "/assets/tech_logo/github.png" },
  { name: "Redux", icon: "/assets/tech_logo/redux.png" },
  { name: "TypeScript", icon: "/assets/tech_logo/typescript.png" },
  { name: "Bootstrap", icon: "/assets/tech_logo/bootstrap.png" },
  { name: "Material UI", icon: "/assets/tech_logo/materialui.png" },
  { name: "Tailwind CSS", icon: "/assets/tech_logo/tailwindcss.png" },
  { name: "Next.js", icon: "/assets/tech_logo/nextjs.png" },
  { name: "Spring Boot", icon: "/assets/tech_logo/springboot.png" },
];
